region                     = "us-east-1"
cluster_name               = "my-eks-cluster"
subnet_ids                 = ["subnet-0f798a592c6b368cd", "subnet-0a57d37ffce7cdb09"]
node_group_name            = "primary"
node_count                 = 3
max_size                   = 5
min_size                   = 2
instance_type              = "t3.medium"
disk_size_gb               = 20
source_security_group_id   = "sg-00448e27b5c6f1f8e" # Replace with your actual security group ID
