name: Destroy Terraform Infrastructure

on:
  push:
    branches:
      - main

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          terraform_version: 1.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1